apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: whoami-cert-and-http
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: http://blackbox-exporter.monitoring.svc:9115
  targets:
    staticConfig:
      static:
        - https://bry.daviacandido.com.br