apiVersion: 1
kind: ConfigMap
metadata:
  name: grafana-datasources-alertmanager
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  alertmanager.yaml: |
    apiVersion: 1
    datasources:
      - name: Alertmanager
        type: alertmanager
        access: proxy
        url: http://alertmanager-main.monitoring.svc:9093