name: infra-deploy

run-name: "Infra Deploy â€” ${{ inputs.comment }} (by @${{ github.actor }})"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment folder (ex: aks)"
        required: true
        default: "aks"
      comment:
        description: "Deployment comment/reason"
        required: false
        default: "Terraform infra deploy triggered manually via GitHub Actions"

permissions:
  contents: read

concurrency:
  group: infra-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra:
    uses: ./.github/workflows/_terraform_infra.yaml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}